### PR TITLE
Fixing Issue #2: Arrow style RFC822 dates and more

### PR DESCRIPTION
**Pull request by greggles**
Fixes the problem I encountered and described in #2. There may be a more flexible way to address this. I admit I'm not strong with Arrow's features.

### CODE REVIEW

**Comment by v-p-b** [comment]
Thanks for working on this! 

This modification actually reduces the number of acceptable formats to two (`arrow.get()` can parse lots of stuff by default), but I couldn't find an accessible set of "usual" formats in arrow that we could extend. 

I think a better solution would be to keep the default parsing (with lots of possible formats built-in), and trying to parse exceptional formats in case of an exception. What do you think?

**Comment by v-p-b** [comment]
I worked on this a bit, does https://github.com/v-p-b/rss2bsky.py/tree/liberal-arrow work for you?

**Comment by greggles** [comment]
This proposal to handle dates using default parsing and then falling back seems great! From my reading of the Arrow docs I didn't think it would consider formats other than ISO-8601, so it seemed good to specify the format that is the RSS standard (even if many feeds don't follow that standard). All that said, I like this proposal more.

I think the liberal-arrow branch won't work for the specific feed I'm testing. I tried using just `FORMAT_RFC2822` but that constant seems to use a 2 digit year while the RFC2822 format specifies a 4 digit year. That's why I added the 4 digit year format string, based on Arrow's defined RFC2822 format. I think if you added `"ddd, DD MMM YYYY HH:mm:ss Z"` as a secondary format to the array then it would work.

**Comment by v-p-b** [comment]
> From my reading of the Arrow docs I didn't think it would consider formats other than ISO-8601

The [source](https://github.com/arrow-py/arrow/blob/f77aa1d4251df9b8d8b48e6bf8b1dbbe2c06a8f7/arrow/parser.py#L191) is quite telling about the complexity `arrow.get()` handles, and you can also look at the examples in the User's Guide:

```
>>> arrow.get('2013-09-30T15:34:00.000-07:00')
<Arrow [2013-09-30T15:34:00-07:00]>
>>> arrow.get('2013-09-30')
<Arrow [2013-09-30T00:00:00+00:00]>
```

> I think the liberal-arrow branch won't work for the specific feed I'm testing. I tried using just FORMAT_RFC2822 but that constant seems to use a 2 digit year while the RFC2822 format specifies a 4 digit year. 

Beware that RFC 822 != RFC 2822: the latter specifies 4-digit years, and this built-in format successfully parses your failing example from #2:
```
>>> arrow.FORMAT_RFC2822
'ddd, DD MMM YYYY HH:mm:ss Z'
>>> arrow.get('Wed, 26 Jun 2024 15:00:57 +0000', [arrow.FORMAT_RFC2822])
<Arrow [2024-06-26T15:00:57+00:00]>
```

Were you able to test the new branch with the failing feed? If there are any more failing cases it would be useful to see them. Also, if you could share affected RSS URL's I could put together some automated tests so we can have better confidence in the parsing code.

**Comment by v-p-b** [comment]
I've been using my fix for some time so I merged it. Thanks for the feedback, please let me know if anything is missing!

**Comment by greggles** [comment]
Sorry I never got time to come back to this. Thanks for your patient help and explanations. I haven't had a chance to test again but will followup if I run into more problems.

**Pull request closed without merging**
